TEMAS_POR_MATERIA = {
  "língua portuguesa": [
  "alfabeto","potuguês", "vogais", "consoantes", "sílabas", "separação silábica", 
  "acentuação gráfica", "regras de acentuação", "hiato", "ditongo", "tritongo", 
  "encontro consonantal", "ortografia oficial", "uso do hífen", "uso de maiúsculas", "abreviações",
  "classes de palavras", "substantivo", "adjetivo", "artigo", "pronome",
  "verbo", "advérbio", "numeral", "preposição", "conjunção", "interjeição",
  "locuções verbais", "formas nominais do verbo", "modo indicativo", "modo subjuntivo", "modo imperativo",
  "tempos verbais simples", "tempos verbais compostos", "voz ativa", "voz passiva", "voz reflexiva",
  "crase", "uso da crase", "regência verbal", "regência nominal", "colocação pronominal",
  "próclise", "ênclise", "mesóclise", "concordância verbal", "concordância nominal",
  "sujeito", "predicado", "predicado nominal", "predicado verbal", "predicado verbo-nominal",
  "tipos de sujeito", "sujeito simples", "sujeito composto", "sujeito oculto", "sujeito indeterminado",
  "objeto direto", "objeto indireto", "objeto direto preposicionado", "objeto indireto pleonástico", "complemento nominal",
  "adjunto adnominal", "adjunto adverbial", "aposto", "vocativo", "orações coordenadas",
  "orações subordinadas", "oração subordinada substantiva", "oração subordinada adjetiva", "oração subordinada adverbial", "período simples",
  "período composto", "orações reduzidas", "oração principal", "oração subordinada desenvolvida", "orações coordenadas assindéticas",
  "orações coordenadas sindéticas", "pontuação", "uso da vírgula", "uso do ponto e vírgula", "uso do travessão",
  "uso de reticências", "uso de aspas", "uso de parênteses", "uso de colchetes", "uso do ponto final",
  "uso do ponto de interrogação", "uso do ponto de exclamação", "uso dos dois pontos", "funções da linguagem", "linguagem denotativa",
  "linguagem conotativa", "variação linguística", "norma culta", "norma popular", "gírias",
  "regionalismos", "neologismos", "empréstimos linguísticos", "figuras de linguagem", "metáfora",
  "metonímia", "hipérbole", "antítese", "paradoxo", "prosopopeia"
],
  
  "literatura": [
  "literatura oral", "literatura escrita", "literatura brasileira", "literatura portuguesa", "literatura universal",
  "gênero lírico", "gênero épico", "gênero dramático", "poesia", "prosa",
  "conto", "crônica", "romance", "novela", "fábula",
  "lenda", "mito", "epopeia", "tragédia", "comédia",
  "classicismo", "humanismo", "trovadorismo", "renascimento", "barroco",
  "arcadismo", "neoclassicismo", "romantismo", "realismo", "naturalismo",
  "parnasianismo", "simbolismo", "pré-modernismo", "modernismo", "literatura contemporânea",
  "primeira fase modernista", "segunda fase modernista", "terceira fase modernista", "literatura pós-moderna", "literatura digital",
  "autores clássicos", "autores contemporâneos", "poesia épica", "poesia lírica", "poesia concreta",
  "poesia marginal", "poesia de cordel", "haicai", "soneto", "ode",
  "elegia", "sátira", "paródia", "intertextualidade", "intermidialidade",
  "figura do narrador", "narrador personagem", "narrador observador", "narrador onisciente", "ponto de vista narrativo",
  "tempo narrativo", "espaço narrativo", "enredo", "clímax", "desfecho",
  "personagem", "personagem plano", "personagem redondo", "herói", "anti-herói",
  "movimentos de vanguarda", "futurismo", "cubismo", "expressionismo", "dadaísmo",
  "surrealismo", "neorrealismo", "literatura engajada", "literatura feminina", "literatura afro-brasileira",
  "literatura indígena", "literatura marginal", "literatura fantástica", "literatura policial", "literatura de terror",
  "literatura de ficção científica", "literatura distópica", "literatura utópica", "literatura infantojuvenil", "literatura de viagens",
  "metaficção", "estilo literário", "figuras de linguagem na literatura", "simbolismo literário", "alegoria",
  "leituras obrigatórias", "clássicos da literatura", "canon literário", "crítica literária", "história da literatura"
],
  
  "produção de texto (redação)": [
  "tipos de redação", "redação dissertativa", "redação argumentativa", "redação narrativa", "redação descritiva",
  "redação injuntiva", "redação expositiva", "redação jornalística", "redação científica", "redação criativa",
  "estrutura do texto", "introdução", "desenvolvimento", "conclusão", "tese",
  "argumento", "exemplo", "citação", "dados estatísticos", "contextualização",
  "parágrafo", "coerência textual", "coesão textual", "encadeamento lógico", "conectivos",
  "coerência argumentativa", "coesão coesiva", "progressão textual", "transições", "revisão textual",
  "planejamento de texto", "rascunho", "versão final", "reescrita", "edição",
  "pontuação", "vírgula", "ponto final", "ponto e vírgula", "dois pontos",
  "interrogação", "exclamação", "uso de travessão", "aspas", "parênteses",
  "acertos gramaticais", "ortografia", "acentuação", "concordância verbal", "concordância nominal",
  "regência verbal", "regência nominal", "colocação pronominal", "crase", "uso de pronomes",
  "vocabulário", "precisão vocabular", "sinônimos", "antônimos", "palavras de transição",
  "coesão lexical", "variedade linguística", "norma culta", "registro formal", "registro informal",
  "argumentação persuasiva", "retórica", "logos", "ethos", "pathos",
  "persuasão textual", "opinião fundamentada", "análise crítica", "comparação", "contraste",
  "exemplificação", "ilustração", "explicação", "conclusão sólida", "síntese",
  "evitar repetição", "clareza", "objetividade", "coerência temática", "foco no tema",
  "análise de proposta", "interpretação de tema", "respeito às normas", "adequação do gênero", "revisão ortográfica",
  "coerência lógica", "exemplos históricos", "referências culturais", "estatísticas", "citações corretas",
  "planejamento de parágrafos", "tópico frasal", "desenvolvimento de ideias", "conclusão eficaz", "técnicas de escrita",
  "autoavaliação", "feedback", "revisão gramatical", "correção de estilo", "melhoria contínua"
],

"língua estrangeira (inglês/espanhol)": [
  "alfabeto", "pronúncia", "fonética", "fonologia", "vogais",
  "consoantes", "acentuação", "dígrafos", "sílabas", "entonação",
  "saudações", "apresentações", "cumprimentos", "despedidas", "expressões básicas",
  "números", "datas", "horas", "meses", "dias da semana",
  "cores", "formas", "objetos", "lugares", "profissões",
  "família", "partes do corpo", "comida", "animais", "roupas",
  "verbos básicos", "verbos regulares", "verbos irregulares", "tempos verbais", "presente simples",
  "passado simples", "futuro simples", "present continuous", "past continuous", "future continuous",
  "present perfect", "past perfect", "future perfect", "modais", "can/could",
  "may/might", "shall/should", "will/would", "must", "ought to",
  "perguntas", "respostas curtas", "yes/no questions", "wh-questions", "question tags",
  "negativa", "adjetivos", "advérbios", "preposições", "conjunções",
  "pronomes pessoais", "pronomes possessivos", "pronomes reflexivos", "pronomes demonstrativos", "pronomes relativos",
  "artigos definidos", "artigos indefinidos", "substantivos contáveis", "substantivos incontáveis", "plural",
  "comparativos", "superlativos", "expressões idiomáticas", "phrasal verbs", "collocations",
  "vocabulário cotidiano", "vocabulário escolar", "vocabulário profissional", "vocabulário de viagens", "vocabulário cultural",
  "leitura de textos", "interpretação de textos", "compreensão auditiva", "listening", "speaking",
  "writing", "writing formal", "writing informal", "email writing", "essay writing",
  "dialogues", "role play", "expressões de opinião", "expressões de concordância", "expressões de discordância",
  "expressões de surpresa", "expressões de emoção", "expressões de tempo", "expressões de lugar", "expressões de quantidade",
  "tradução", "cognatos", "falsos cognatos", "diferenças culturais", "costumes",
  "literatura em inglês", "literatura em espanhol", "música", "filmes", "teatro",
  "expressões idiomáticas espanhol", "verbos regulares espanhol", "verbos irregulares espanhol", "presente de indicativo espanhol", "pretérito perfeito espanhol",
  "pretérito imperfeito espanhol", "futuro espanhol", "subjuntivo espanhol", "imperativo espanhol", "vocabulário cotidiano espanhol"
],

"matemática": [
  "números naturais", "fatorial","números inteiros", "números racionais", "números irracionais", "números reais",
  "operações básicas", "adição", "subtração", "multiplicação", "divisão",
  "potenciação", "radiciação", "raízes quadradas", "raízes cúbicas", "exponenciais",
  "logaritmos", "frações", "frações equivalentes", "frações impróprias", "frações próprias",
  "frações mistas", "porcentagem", "juros simples", "juros compostos", "regra de três simples",
  "regra de três composta", "proporcionalidade direta", "proporcionalidade inversa", "razão", "proporção",
  "equações do 1º grau", "equações do 2º grau", "inequações", "sistemas lineares", "expressões algébricas",
  "polinômios", "fatoração", "produtos notáveis", "identidades algébricas", "funções",
  "função do 1º grau", "função do 2º grau", "função exponencial", "função logarítmica", "função modular",
  "função quadrática", "função afim", "função linear", "gráficos de funções", "análise de gráficos",
  "progressões aritméticas", "progressões geométricas", "sequências", "soma de termos", "número de termos",
  "matriz", "determinante", "operações com matrizes", "vetores", "produto escalar",
  "geometria plana", "ponto", "reta", "segmento de reta", "ângulos",
  "triângulos", "quadriláteros", "polígonos", "círculo", "circunferência",
  "área", "perímetro", "volume", "geometria espacial", "sólidos geométricos",
  "trigonometria", "seno", "cosseno", "tangente", "lei dos senos",
  "lei dos cossenos", "triângulos retângulos", "funções trigonométricas", "identidades trigonométricas", "transformações geométricas",
  "estatística", "média aritmética", "mediana", "moda", "desvio padrão",
  "probabilidade", "experimentos aleatórios", "eventos", "probabilidade condicional", "combinatória",
  "números complexos", "conjugado", "módulo", "argumento", "polinômios complexos",
  "análise combinatória", "permutação", "combinação", "arranjo", "binômio de Newton"
],

"física": [
  "grandezas físicas", "medidas e unidades", "sistema internacional (SI)", "escala de grandezas", "dimensões físicas",
  "vetores", "operacoes com vetores", "deslocamento", "velocidade", "aceleração",
  "movimento retilíneo uniforme (MRU)", "movimento retilíneo uniformemente variado (MRUV)", "queda livre", "lançamento vertical", "queda de corpos",
  "movimento circular uniforme", "frequência", "período", "aceleração centrípeta", "velocidade angular",
  "leis de Newton", "primeira lei de Newton", "segunda lei de Newton", "terceira lei de Newton", "força",
  "peso", "massa", "força resultante", "atrito", "forças em planos inclinados",
  "trabalho", "energia", "energia cinética", "energia potencial", "teorema da energia cinética",
  "energia mecânica", "conservação da energia", "potência", "força elástica", "lei de Hooke",
  "quantidade de movimento", "impulso", "colisões elásticas", "colisões inelásticas", "momentum angular",
  "gravitação universal", "lei da gravitação", "campo gravitacional", "aceleração da gravidade", "órbitas planetárias",
  "pressão", "densidade", "empuxo", "princípio de Arquimedes", "flutuabilidade",
  "termodinâmica", "temperatura", "calor", "capacidade térmica", "calor específico",
  "equação de calor", "mudança de fase", "leis da termodinâmica", "máquinas térmicas", "entropia",
  "ondas", "ondas mecânicas", "ondas sonoras", "ondas eletromagnéticas", "frequência",
  "comprimento de onda", "amplitude", "interferência", "reflexão", "refração",
  "difração", "polarização", "princípio de superposição", "efeito Doppler", "velocidade do som",
  "óptica", "reflexão da luz", "refração da luz", "lentes", "espelhos",
  "imagem real", "imagem virtual", "convergente", "divergente", "formação de imagens",
  "eletrostática", "carga elétrica", "lei de Coulomb", "campo elétrico", "potencial elétrico",
  "diferença de potencial", "capacitores", "corrente elétrica", "resistência elétrica", "leis de Ohm",
  "circuitos elétricos", "associacao de resistores", "associacao de capacitores", "magnetismo", "campo magnético",
  "força magnética", "indução eletromagnética", "Lei de Faraday", "Lei de Lenz", "ondas eletromagnéticas"
],

"química": [
  "átomo", "partículas subatômicas", "número atômico", "massa atômica", "isótopos",
  "tabela periódica", "grupos e períodos", "famílias químicas", "metais", "não metais",
  "gases nobres", "halogênios", "alcalinos", "alcalino-terrosos", "blocos s, p, d, f",
  "ligação química", "ligação iônica", "ligação covalente", "ligação metálica", "ligação de hidrogênio",
  "forças intermoleculares", "van der Waals", "polaridade", "dipolo", "moléculas apolares",
  "química orgânica", "hidrocarbonetos", "alcanos", "alcenos", "alcinos",
  "aromáticos", "funções orgânicas", "álcoois", "éteres", "aldeídos",
  "cetonas", "ácidos carboxílicos", "ésteres", "aminas", "amidas",
  "polímeros", "plásticos", "biomoléculas", "carboidratos", "proteínas",
  "lipídios", "enzimas", "reação química", "tipos de reação", "equação química",
  "balanceamento químico", "estequiometria", "conservação de massa", "leis ponderais", "leis volumétricas",
  "soluções", "solubilidade", "concentração", "molaridade", "molalidade",
  "normalidade", "diluição", "misturas", "suspensões", "coloides",
  "pH", "indicadores", "ácidos", "bases", "sais",
  "reação ácido-base", "neutralização", "titulometria", "oxidação", "redução",
  "redox", "eletrólise", "potencial padrão", "termodinâmica química", "entalpia",
  "entropia", "energia livre de Gibbs", "cinética química", "velocidade da reação", "fatores de reação",
  "equilíbrio químico", "constante de equilíbrio", "solubilidade de sais", "pressão", "gases",
  "leis dos gases", "volume molar", "condições normais", "gas ideal", "mistura gasosa",
  "química ambiental", "poluição", "tratamento de água", "resíduos sólidos", "reciclagem",
  "química industrial", "processos químicos", "reagentes", "catalisadores", "energias de ativação"
],

"biologia": [
  "célula", "célula animal", "célula vegetal", "organelas celulares", "núcleo",
  "mitocôndrias", "ribossomos", "retículo endoplasmático", "complexo golgiense", "lisossomos",
  "peroxissomos", "cloroplastos", "membrana plasmática", "parede celular", "citoplasma",
  "difusão", "osmose", "transporte ativo", "endocitose", "exocitose",
  "tecido epitelial", "tecido conjuntivo", "tecido muscular", "tecido nervoso", "sistema esquelético",
  "sistema muscular", "sistema nervoso", "sistema endócrino", "sistema circulatório", "sistema respiratório",
  "sistema digestório", "sistema excretor", "sistema imunológico", "sistema reprodutor", "hormônios",
  "enzimas", "metabolismo", "fotossíntese", "respiração celular", "fermentação",
  "cadeia alimentar", "teia alimentar", "produtores", "consumidores", "decompositores",
  "ecossistema", "bioma", "biosfera", "população", "comunidade",
  "cadeia trófica", "sucessão ecológica", "equilíbrio ecológico", "recursos naturais", "conservação ambiental",
  "genética", "DNA", "RNA", "replicação", "transcrição",
  "tradução", "mutação", "hereditariedade", "leis de Mendel", "genótipo",
  "fenótipo", "alelos", "dominante", "recessivo", "codominância",
  "herança ligada ao sexo", "herança poligênica", "engenharia genética", "biotecnologia", "clonagem",
  "evolução", "seleção natural", "seleção artificial", "adaptação", "especiação",
  "Darwinismo", "Lamarckismo", "teoria sintética da evolução", "fósseis", "registro fóssil",
  "microbiologia", "bactérias", "vírus", "fungos", "protozoários",
  "reino vegetal", "reino animal", "reino fungi", "reino protista", "reino monera",
  "respiração aeróbica", "respiração anaeróbica", "nutrição", "digestão", "absorção de nutrientes",
  "reprodução sexual", "reprodução assexual", "ciclo celular", "mitose", "meiose"
],

"história": [
  "pré-história", "idade da pedra", "idade do bronze", "idade do ferro", "sociedades pré-históricas",
  "civilizações antigas", "Mesopotâmia", "Egito antigo", "Grécia antiga", "Roma antiga",
  "Império Bizantino", "Império Romano do Ocidente", "Idade Média", "Alta Idade Média", "Baixa Idade Média",
  "feudalismo", "sociedade feudal", "cultura medieval", "igreja medieval", "cruzadas",
  "Renascimento", "Humanismo", "Renascimento italiano", "Renascimento europeu", "Expansão marítima",
  "descobrimentos", "colonização", "colonização da América", "colonização do Brasil", "tráfico negreiro",
  "Reforma Protestante", "Contrarreforma", "Absolutismo", "monarquias europeias", "Iluminismo",
  "Revolução Industrial", "maquinário", "industrialização", "urbanização", "condições de trabalho",
  "Revolução Francesa", "Queda da Bastilha", "Direitos do Homem", "Napoleão Bonaparte", "Guerras Napoleônicas",
  "Revoluções liberais", "independência dos EUA", "independência da América Latina", "independência do Brasil", "Período Colonial",
  "Período Imperial", "Primeira República", "Era Vargas", "Ditadura Militar", "Redemocratização",
  "Primeira Guerra Mundial", "Segunda Guerra Mundial", "Tratado de Versalhes", "Holocausto", "Revolução Russa",
  "Guerra Fria", "bloco ocidental", "bloco oriental", "queda do muro de Berlim", "União Europeia",
  "movimentos sociais", "feminismo", "movimento negro", "movimento operário", "sufrágio feminino",
  "colonialismo", "imperialismo", "neocolonialismo", "descolonização", "globalização",
  "história econômica", "capitalismo", "socialismo", "comunismo", "mercantilismo",
  "história cultural", "arte medieval", "arte renascentista", "arte barroca", "arte moderna", "arte contemporânea",
  "história da ciência", "cientistas famosos", "descobertas científicas", "inovações tecnológicas", "história da educação",
  "história da religião", "cristianismo", "islamismo", "judaísmo", "budismo",
  "história da política", "formação de estados", "constituições", "partidos políticos", "eleições", "guerra fria"
],

"geografia": [
  "cartografia", "mapas", "projeções cartográficas", "coordenadas geográficas", "meridianos",
  "paralelos", "latitude", "longitude", "fusos horários", "GPS",
  "geomorfologia", "relevo", "montanhas", "planícies", "vales",
  "hidrografia", "rios", "lagos", "açudes", "oceanos",
  "climatologia", "clima", "temperatura", "umidade", "precipitação",
  "biomas", "floresta tropical", "floresta temperada", "cerrado", "caatinga",
  "pampa", "pantanal", "tundra", "taiga", "desertos",
  "solo", "tipos de solo", "erosão", "fertilidade", "agricultura",
  "vegetação", "flora", "fauna", "recursos naturais", "minérios",
  "recursos hídricos", "energia hidrelétrica", "energia solar", "energia eólica", "energia geotérmica",
  "população", "densidade demográfica", "migração", "urbanização", "meio urbano",
  "meio rural", "regiões metropolitanas", "globalização", "economia global", "blocos econômicos",
  "geopolítica", "fronteiras", "território", "soberania", "conflitos internacionais",
  "geografia econômica", "industrialização", "agricultura", "comércio internacional", "setor primário",
  "setor secundário", "setor terciário", "meio ambiente", "sustentabilidade", "desenvolvimento sustentável",
  "poluição", "desmatamento", "aquecimento global", "mudanças climáticas", "desastres naturais",
  "terremotos", "tsunamis", "erupções vulcânicas", "deslizamentos", "inundações",
  "cartografia temática", "mapa físico", "mapa político", "mapa climático", "mapa econômico",
  "urbanismo", "planejamento urbano", "habitação", "transporte", "infraestrutura",
  "geografia cultural", "costumes regionais", "línguas", "religião", "tradições",
  "geografia histórica", "colonização", "formação territorial", "expansão urbana", "migrações históricas",
  "geografia política", "Estados-nação", "organismos internacionais", "ONU", "OTAN"
],
  "filosofia": [
    "filosofia grega", "pré-socráticos", "Sócrates", "Platão", "Aristóteles",
    "filosofia medieval", "Agostinho de Hipona", "Tomás de Aquino", "escolástica", "filosofia renascentista",
    "humanismo", "filosofia moderna", "Descartes", "Spinoza", "Leibniz",
    "Locke", "Hobbes", "Rousseau", "Kant", "Hegel",
    "filosofia contemporânea", "Nietzsche", "Marx", "Sartre", "Heidegger",
    "Foucault", "Habermas", "filosofia oriental", "confucionismo", "taoismo",
    "budismo", "ética", "ética normativa", "ética aplicada", "ética kantiana",
    "ética utilitarista", "moral", "virtude", "justiça", "liberdade",
    "política", "contrato social", "direitos humanos", "democracia", "cidadania",
    "metafísica", "ontologia", "epistemologia", "gnoseologia", "filosofia da ciência",
    "lógica", "lógica formal", "silogismo", "falácias", "argumentação",
    "estética", "beleza", "arte", "expressão", "crítica",
    "existencialismo", "absurdismo", "fenomenologia", "hermenêutica", "pragmatismo",
    "positivismo", "realismo", "idealismo", "materialismo", "dialética",
    "filosofia política", "justiça social", "igualdade", "libertação", "autoridade",
    "poder", "sociedade", "filosofia da linguagem", "semântica", "pragmática",
    "filosofia da mente", "consciência", "intencionalidade", "inteligência artificial", "identidade pessoal",
    "filosofia da educação", "pedagogia", "educação crítica", "educação inclusiva", "formação ética",
    "filosofia da história", "progresso", "determinismo", "historicismo", "civilização",
    "filosofia da religião", "teísmo", "ateísmo", "agnosticismo", "misticismo",
    "liberdade de pensamento", "tolerância", "questionamento", "reflexão", "racionalidade"
  ],
  "sociologia": [
    "sociedade", "cultura", "subcultura", "classe social", "estratificação social",
    "mobilidade social", "desigualdade", "poder", "autoridade", "dominação",
    "instituições sociais", "família", "escola", "religião", "estado",
    "trabalho", "mercado", "economia", "sociedade civil", "movimentos sociais",
    "socialização", "agentes de socialização", "normas sociais", "valores", "crença",
    "etnia", "raça", "gênero", "sexualidade", "identidade",
    "comportamento social", "interação social", "grupos sociais", "grupo primário", "grupo secundário",
    "rede social", "coletividade", "massa", "multidão", "cultura de massa",
    "globalização", "sociedade pós-moderna", "sociedade digital", "tecnologia", "internet",
    "cibercultura", "mídia", "informação", "consumo", "cultura popular",
    "sociologia clássica", "Durkheim", "Marx", "Weber", "Simmel",
    "teorias contemporâneas", "teoria crítica", "funcionalismo", "interacionismo simbólico", "pós-estruturalismo",
    "desigualdade social", "exclusão social", "preconceito", "discriminação", "racismo",
    "sexismo", "homofobia", "movimento negro", "feminismo", "direitos humanos",
    "violência", "criminalidade", "prisão", "pena", "justiça social",
    "educação", "alfabetização", "acesso à educação", "política educacional", "formação cidadã",
    "trabalho e sociedade", "organização do trabalho", "emprego", "produção", "economia global",
    "população", "demografia", "migração", "urbanização", "meio ambiente",
    "desenvolvimento sustentável", "consumo consciente", "cultura digital", "redes sociais", "cibercultura"
  ],
  "educação física": [
    "saúde", "qualidade de vida", "aptidão física", "resistência", "força",
    "flexibilidade", "coordenação motora", "agilidade", "equilíbrio", "velocidade",
    "alongamento", "aquecimento", "resfriamento", "prevenção de lesões", "biomecânica",
    "anatomia", "sistema muscular", "sistema esquelético", "sistema cardiovascular", "sistema respiratório",
    "esportes coletivos", "futebol", "basquete", "voleibol", "handebol",
    "esportes individuais", "atletismo", "natação", "ginástica", "ciclismo",
    "regras esportivas", "arbitragem", "táticas", "estratégias", "fair play",
    "condicionamento físico", "treinamento de força", "treinamento aeróbico", "treinamento anaeróbico", "resistência muscular",
    "nutrição esportiva", "hidratação", "energia", "suplementação", "recuperação",
    "cultura corporal", "dança", "expressão corporal", "luta", "artes marciais",
    "atividade física para todas as idades", "educação física escolar", "inclusão", "esporte adaptado", "lazer",
    "avaliação física", "testes de aptidão", "monitoramento de desempenho", "registro de treinos", "planejamento de treino",
    "competição", "motivação", "cooperação", "espírito esportivo", "resiliência",
    "psicologia do esporte", "concentração", "controle emocional", "superação", "foco",
    "saúde mental", "estresse", "ansiedade", "meditação", "respiração",
    "habilidades motoras", "coordenação olho-mão", "coordenação motora fina", "coordenação motora grossa", "percepção espacial",
    "educação para a saúde", "prevenção de doenças", "atividade física regular", "programas de saúde", "bem-estar"
  ],
  "artes": [
    "história da arte", "arte rupestre", "arte egípcia", "arte grega", "arte romana",
    "arte medieval", "arte renascentista", "barroco", "rococó", "neoclassicismo",
    "romantismo", "realismo", "impressionismo", "modernismo", "arte contemporânea",
    "artes visuais", "pintura", "escultura", "desenho", "gravura",
    "fotografia", "design", "arquitetura", "ilustração", "arte digital",
    "música", "história da música", "teoria musical", "harmonia", "melodia",
    "ritmo", "percussão", "instrumentos musicais", "composição", "interpretação",
    "teatro", "história do teatro", "atores", "encenação", "cenografia",
    "direção teatral", "dramaturgia", "expressão corporal", "improvisação", "teatro musical",
    "dança", "história da dança", "ballet", "dança contemporânea", "dança popular",
    "coreografia", "expressão corporal", "performance", "ritmo", "coordenação motora",
    "arte cênica", "literatura dramática", "interpretação", "palco", "plateia",
    "crítica de arte", "análise artística", "estética", "interpretação de obras", "movimentos artísticos",
    "arte experimental", "instalação", "performance art", "street art", "grafite",
    "arte e tecnologia", "arte digital", "design gráfico", "animação", "realidade virtual",
    "arte e sociedade", "cultura", "identidade cultural", "patrimônio", "expressão artística",
    "educação artística", "aprendizagem", "criação", "oficina de arte", "atelier",
    "artes integradas", "projetos artísticos", "colaboração", "interdisciplinaridade", "expressão criativa"
  ]

}