TEMAS_POR_MATERIA = {
    "historia": [
        "antiguidade", "antiguidade tardia", "idade antiga", 
        "mesopotamia", "mesopotâmia",
        "egito antigo", "hebreus", "faraós", "persas",
        "civilizacoes pre colombianas", "civilizações pré-colombianas",
        "inca", "ínca", "asteca", "maía", "maia", 
        "grecia", "grécia", "atenas", "esparta", 
        "roma", "imperio romano", "império romano", "queda de roma",
        "idade media", "idade média", "feudalismo",
        "cruzadas", "renascimento", "reforma protestante",
        "contrarreforma", "expansao maritima", "expansão marítima", 
        "colonizacao da america", "colonização da america", 
        "colonizacao do brasil", "colonização do brasil", "engenho", 
        "pacto colonial", "inconfidencia", "inconfidência", 
        "revoltas coloniais", "confederacao do equador",
        "configurações coloniais", "revolucao francesa",
        "revolução francesa", "revolucao industrial",
        "revolução industrial", "primavera dos povos",
        "liberalismo", "hegemonia burguesa",
        "independencia do brasil", "independência do brasil",
        "dom pedro", "joao vi", "joão vi", "imperio",
        "monarquia", "regencia", "regência", "segundo reinado",
        "abolicao", "abolição", "republica", "república",
        "era vargas", "estado novo", "ditadura", "ai5",
        "ai-5", "diretas ja", "diretas já", "constituicao de 88",
        "constituição de 88", "nova republica",
        "nova república", "primeira guerra mundial",
        "segunda guerra mundial", "guerra fria", "guerra do vietnam",
        "vietnam", "guerra do vietnã", "coreia", "guerra da coreia",
        "revolucao russa", "revolução russa", "crise de 29",
        "queda muro de berlim", "muro de berlim", "berlim",
        "neoliberalismo", "globalizacao", "globalização", "quilombolas"
    ],
    "geografia": [
        "cartografia", "coordenadas geograficas", "coordenadas geográficas",
        "fusos horarios", "fusos horários", "estrutura da terra",
        "placas tectonicas", "placas tectônicas", "terremotos", "vulcoes",
        "vulcões", "relevo brasileiro", "climas do brasil",
        "climas do brasil", "hidrografia do brasil", "vegetacao brasileira",
        "vegetação brasileira", "biomas do mundo", "solos", "erosao",
        "erosão", "zonas termicas", "zonas térmicas",
        "dinamica populacional", "dinâmica populacional",
        "indices demograficos", "índices demográficos",
        "migracao", "migração", "urbanizacao", "urbanização",
        "favelizacao", "favelização", "periferia",
        "geografia agraria", "agricultura familiar",
        "industria", "indústria", "fontes de energia",
        "matriz energetica", "matriz energética",
        "transporte", "logistica", "logística",
        "comercio exterior", "comércio exterior", "globalizacao",
        "globalização", "blocos economicos",
        "blocos econômicos", "mercosul", "geopolitica",
        "geopolítica", "conflitos territoriais",
        "recursos naturais", "impactos ambientais",
        "sustentabilidade", "desigualdade regional",
        "regioes brasileiras", "regiões brasileiras",
        "meio ambiente", "desmatamento", "climatologia",
        "geografia urbana", "crescimento desordenado",
        "tecnologia", "geolocalizacao", "geolocalização",
        "cartografia digital", "sensoriamento remoto",
        "georreferenciamento", "geoestatistica", "geoestatística"
    ],
    "matematica": [
        "numeros reais", "números reais", "operacoes basicas",
        "operações básicas", "expressoes numericas", "expressões numéricas",
        "equacoes primeiro grau", "equações primeiro grau",
        "equacoes segundo grau", "equações segundo grau",
        "sistemas lineares", "funcoes", "função afim", "funções",
        "funcao afim", "funcao quadratica", "função quadrática",
        "funcao exponencial", "função exponencial",
        "funcao logaritmica", "função logarítmica",
        "funcao modular", "função modular", "equacoes e inequacoes",
        "equações e inequações", "matrizes", "determinantes",
        "analise combinatoria", "análise combinatória",
        "probabilidade", "estatistica", "estatística",
        "media", "média", "moda", "mediana", "graficos", "gráficos",
        "tabelas", "geometria plana", "teorema de pitagoras",
        "teorema de pitágoras", "area figuras planas",
        "área figuras planas", "geometria espacial",
        "volume", "geometria analitica", "geometria analítica",
        "distancia", "distância", "equacao da reta",
        "equação da reta", "trigonometria", "circulo trigonometrico",
        "círculo trigonométrico", "identidades trigonometricas",
        "identidades trigonométricas", "numeros complexos",
        "números complexos", "polinomios", "polinômios",
        "sequencias numericas", "sequências numéricas",
        "juros simples", "juros compostos", "porcentagem",
        "regra de tres", "regra de três", "razao e proporcao",
        "razão e proporção", "juros", "progressões",
        "pa, pg", "progressão aritmética", "progressão geométrica"
    ],
    "fisica": [
        "grandezas fisicas", "grandezas físicas", "unidades de medida",
        "medidas", "vetores", "movimento uniforme", "movimento uniformemente variado",
        "queda livre", "movimento circular", "leis de newton",
        "lei de newton", "força peso", "forca peso", "forca de atrito",
        "força de atrito", "trabalho", "energia", "potencia mecanica",
        "potência mecânica", "energia cinetica", "energia cinética",
        "conservacao energia", "conservação de energia", "impulso",
        "quantidade de movimento", "momento", "pressao", "pressão",
        "hidrostatica", "hidrostática", "princípio de pascal",
        "principio de pascal", "princípio de arquimedes",
        "principio de arquimedes", "termologia", "calor", "temperatura",
        "capacidade termica", "capacidade térmica", "dilatação térmica",
        "dilatacao termica", "mudanças de estado", "mudancas de estado",
        "termodinamica", "termodinâmica", "reflexao", "reflexão",
        "refração", "refracao", "espelhos", "lentes", "eletrostatica",
        "eletrostática", "lei de coulomb", "lei de óhm", "leis de ohm",
        "circuitos eletricos", "circuitos elétricos", "magnetismo",
        "lei de faraday", "ondas mecanicas", "ondas mecânicas",
        "som", "acustica", "acústica", "efeito doppler",
        "interferencia", "interferência", "difração", "difração"
    ],
    "quimica": [
        "materia", "matéria", "propriedades", "substancias puras",
        "substâncias puras", "misturas", "separacao de misturas",
        "separação de misturas", "modelos atomicos", "modelos atômicos",
        "estrutura atomica", "estrutura atômica", "configuracao eletronica",
        "configuração eletrônica", "tabela periodica",
        "tabela periódica", "propriedades periodicas",
        "propriedades periódicas", "ligacoes quimicas",
        "ligações químicas", "forcas intermoleculares",
        "funcoes inorganicas", "funções inorgânicas", "acidos",
        "ácidos", "bases", "sais", "oxidos", "óxidos",
        "reacoes quimicas", "reações químicas", "balanço de equacoes",
        "balanço de equações", "estequiometria", "rendimento",
        "gases ideais", "solucoes", "soluções", "concentracao",
        "concentração", "diluicao", "diluição", "solubilidade",
        "reacoes acido base", "reações ácido‑base",
        "reacoes oxirredução", "reações oxirredução",
        "eletroquimica", "eletroquímica", "pilhas", "eletrose",
        "termoquimica", "termoquímica", "entalpia", "cinética química",
        "cinetica quimica", "equilibrio quimico",
        "equilíbrio químico", "pH", "pOH", "química orgânica",
        "quimica organica", "hidrocarbonetos", "funcoes organicas",
        "funções orgânicas", "isomeria", "reações organicas",
        "reações orgânicas", "polimeros", "polímeros",
        "quimica ambiental", "química ambiental", "química do cotidiano"
    ],
    "biologia": [
        "seres vivos", "organizacao celular", "organização celular",
        "organelas", "membrana plasmatica", "membrana plasmática",
        "transporte celular", "metabolismo", "enzimas",
        "respiracao celular", "respiração celular", "fotossintese",
        "fotossíntese", "reproducao celular", "reprodução celular",
        "mitose", "meiose", "genetica", "genética", "leis de mendel",
        "leis de Mendel", "DNA", "RNA", "mutacoes", "mutações",
        "biotecnologia", "clonagem", "transgenicos", "transgênicos",
        "sistemas do corpo humano", "digestorio", "digestório",
        "respiratorio", "respiratório", "circulatorio", "circulatório",
        "excretor", "reprodutor", "nervoso", "endocrino", "endócrino",
        "imunologia", "doencas", "doenças", "parasitologia",
        "reinos biologicos", "reinos biológicos", "virus", "vírus",
        "bacterias", "bactérias", "protistas", "fungos", "plantas",
        "animais", "evolucao", "evolução", "darwinismo", "neodarwinismo",
        "especiacao", "especiação", "ecologia", "ecosistemas",
        "cadeia alimentar", "relações ecológicas", "ciclos biogeoquimicos",
        "ciclos biogeoquímicos", "sustentabilidade", "impactos ambientais",
        "preservacao ambiental", "preservação ambiental"
    ],
    "filosofia": [
        "presocraticos", "pré-socráticos", "pré socráticos", "socrates",
        "sócrates", "platao", "platão", "aristoteles", "aristóteles",
        "estoicismo", "epicurismo", "filosofia medieval", "patrística",
        "escolástica", "santo agostinho", "santo tomás de aquino",
        "racionalismo", "empirismo", "iluminismo", "kant",
        "ética", "moral", "filosofia moderna", "liberdade",
        "existencialismo", "nietzsche", "filosofia política",
        "marxismo", "foucault", "habermas", "derrida", "heidegger"
    ],
    "sociologia": [
        "introducao", "introdução", "durkheim", "marx", "weber",
        "cultura", "etnocentrismo", "relativismo",
        "socializacao", "socialização", "instituicoes sociais",
        "instituições sociais", "familia", "família",
        "educacao", "educação", "mobilidade social",
        "desigualdade", "classes sociais", "cidadania",
        "democracia", "poder", "estado", "movimentos sociais",
        "trabalho", "meios de comunicacao", "meios de comunicação",
        "consumo", "juventude", "gênero", "genero", "raça",
        "raca", "violencia", "violência", "exclusao", "exclusão",
        "modernidade", "pós-modernidade", "pos modernidade",
        "globalizacao", "globalização"
    ],
    "portugues": [
        "interpretacao de texto", "interpretação de texto",
        "compreensao leitora", "compreensão leitora",
        "tipos textuais", "generos textuais", "gêneros textuais",
        "funcoes da linguagem", "funções da linguagem",
        "figuras de linguagem", "coerencia", "coesao", "coesão",
        "variacoes linguisticas", "variações linguísticas",
        "registro formal", "morfologia", "substantivo",
        "adjetivo", "verbo", "adverbio", "advérbio",
        "conjuncao", "conjunção", "sintaxe", "termos da oracao",
        "oração", "periodo composto", "período composto",
        "coordenacao", "coordenação", "subordinacao", "subordinação",
        "pontuacao", "pontuação", "crase", "concordancia verbal",
        "concordância verbal", "concordancia nominal",
        "concordância nominal", "regencia", "regência",
        "ortografia", "semantica", "semântica",
        "denotacao", "denotação", "conotacao", "conotação",
        "literatura brasileira", "escolas literarias",
        "trovadorismo", "humanismo", "classicismo",
        "barroco", "arcadismo", "romantismo", "realismo",
        "naturalismo", "parnasianismo", "simbolismo",
        "modernismo", "pós‑modernismo", "pos modernismo"
    ],
    "redacao": [
        "estrutura", "dissertativo argumentativo",
        "tese", "argumentos", "introducao", "introdução",
        "desenvolvimento", "conclusao", "conclusão",
        "estrategias", "estratégias", "coesao", "coerencia",
        "conectivos", "repertorio sociocultural",
        "repertório sociocultural", "intervencao", "intervenção",
        "criterios enem", "critérios enem", "registro formal",
        "planejamento", "temas atuais", "temas históricos",
        "temas historicos", "dados", "citações", "citacoes",
        "fuga ao tema", "voz ativa", "paragrafo estruturado",
        "parágrafo estruturado"
    ],
}
